account_id = "8842d546fe1eb2fc8a677352e208ac13"
name = "the-archive-status-page"
main = "./src/worker/index.ts"
compatibility_flags = [ "streams_enable_constructors" ]
compatibility_date = "2021-09-29"
workers_dev = true
# npx --no -- wrangler kv:namespace create cf-worker-status-page-pro
kv_namespaces = [ { binding = "KV_STORE", id = "f24d7910903d4d1fb8001920dd6d5a8c" }, ]

[site]
bucket = "./dist/client"

[dev]
port = 3000

[env.production]
kv_namespaces = [ { binding = "KV_STORE", id = "f24d7910903d4d1fb8001920dd6d5a8c" }, ]

[env.production.triggers]
crons = [
  # https://crontab.guru/#*/5_*_*_*_*
  # Check monitors
  "*/5 * * * *",
  # https://crontab.guru/#*/10_*_*_*_*
  # Update remote csv monitors
  "*/10 * * * *",
]
